### ISSUE TITLE
Cannot see total audio time

### ISSUE THREAD

**Issue by Jitendra-PG** [riyaddecoder/react-audio-play#9]
With my current implementation I am not seeing the total time of the audio.
I am using an audio blob and creating a URL and supplying it to the player `src`. Below is how I am using it
```
<AudioPlayer 
    src={URL.createObjectURL(props.recordingBlob)}
    color="white"
    sliderColor="white"
    style={{ background: '#5865F2', borderRadius: '20px', padding: '30px', width: '100%' }}
/>
```

Below is how I see it. As you can see, I do not see the total audio time
<img width="464" alt="image" src="https://github.com/user-attachments/assets/60929c8d-dfa3-4a26-80df-ceda6ad55e1a">

**Comment by riyaddecoder** [comment]
@Jitendra-PG Thank you for trying the package! The issue with **URL.createObjectURL(audioBlob)** not showing the full duration right away is common. It happens because the browser needs time to load the audio. The issue is fixed, and the full duration will now display once the audio is fully processed. Please use version v1.0.3 or later.
